spring:
  datasource:
    url: jdbc:mysql://localhost:3306/interview
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

ligg:
  name: 大都督

#自定义starter的配置文件
liggstarter:
  token-redis-host: 127.0.0.1
  token-redis-pwd: 123456